version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wildberries-proxy
      MYSQL_USER: root1
      MYSQL_PASSWORD: root1
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
    app-network:
